export type AgreementTemplate = { kind: "MEMBERSHIP" | "PROJECT"; title: string; body: string; version: number };
export type Agreement = { id: string; ownerKey: string; scope: string; attempt: number; kind: string; title: string; body: string; contextText: string; templateVersion: number; documentHash: string; signerName: string; contact: string; state: "PENDING" | "CHANGES_REQUESTED" | "DEMO_ACTIVE"; reviewNote: string; reviewer: string; createdAt: string; reviewedAt: string | null };
export type AgreementData = { placeholder: true; ready: boolean; templates: AgreementTemplate[]; contracts: Agreement[]; projects: { id: string; title: string; episodeCount: number; stage: string }[] };
export const agreementLabels = { PENDING: "待平台確認", CHANGES_REQUESTED: "退回修改", DEMO_ACTIVE: "演示確認完成" };
export function latestAgreement(rows: Agreement[], scope: string) { return rows.filter(row => row.scope === scope).sort((a,b) => b.attempt-a.attempt)[0]; }
const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
export function agreementDocument(doc: { title: string; body: string; contextText?: string; templateVersion?: number; signerName?: string; contact?: string; createdAt?: string; state?: Agreement["state"]; id?: string; documentHash?: string; reviewNote?: string; reviewedAt?: string | null }) {
  const fields = [["記錄編號", doc.id || "尚未提交"], ["模板版本",doc.templateVersion], ["確認姓名",doc.signerName], ["聯絡資料",doc.contact], ["提交時間",doc.createdAt], ["狀態",doc.state ? agreementLabels[doc.state] : "未提交"], ["平台確認時間",doc.reviewedAt], ["平台意見",doc.reviewNote], ["文件校驗值 SHA-256",doc.documentHash]].filter(([,v]) => v !== undefined && v !== null && v !== "");
  return `<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>${escapeHtml(doc.title)}</title><style>body{max-width:850px;margin:40px auto;padding:24px;font:16px/1.8 sans-serif;color:#222}aside{border:2px solid #bd8c3d;padding:16px;background:#fff8e8}pre{white-space:pre-wrap;font:inherit}dt{font-weight:bold}dd{margin:0 0 12px;overflow-wrap:anywhere}</style><h1>${escapeHtml(doc.title)}</h1><aside>佔位文件 · 僅供流程演示 · 非正式合同<br>本記錄不代表正式簽約，不作為授權、收益分成或付款依據。正式文件須另行簽署。</aside><pre>${escapeHtml(doc.contextText || "")}</pre><pre>${escapeHtml(doc.body)}</pre><h2>本次確認記錄</h2><dl>${fields.map(([k,v]) => `<dt>${escapeHtml(k)}</dt><dd>${escapeHtml(v)}</dd>`).join("")}</dl></html>`;
}
