import { ArticleCategorySchema, ArticleSchema, BusinessPageSchema, DownloadSettingsSchema, DramaCategorySchema, DramaSchema, HomePageSchema, LegalPageSchema, NavigationItemSchema, SiteSettingsSchema, type Article, type ArticleCategory, type BusinessPage, type Creator, type DownloadSettings, type Drama, type DramaCategory, type HomePage, type LegalDocument, type NavigationItem, type Site } from "@/content/types";
import type { ContentRepository, ListOptions } from "@/content/repositories";
import { filterProductionContent, sanitizeDownloadSettings } from "@/content/validation";

const placeholderPoster = { src: "/cms-media/video/drama-promo-poster.jpg", alt: "My Dream 內容預覽", isPlaceholder: true };
const localContent = {
  site: { id: "site" as const, name: "My Dream", locale: "zh-Hant" as const, siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://mydream.example.com", defaultSeo: { title: "My Dream｜短劇 × 創作者影音平台", description: "追劇，是開始。創作，才是你的主場。", canonicalPath: "/" }, socialLinks: {} },
  navigation: [{ id: "home", label: "首頁", href: "/", order: 0, visibility: "published" as const }, { id: "explore", label: "探索短劇", href: "/explore", order: 1, visibility: "published" as const }, { id: "creator", label: "創作者", href: "/creator", order: 2, visibility: "published" as const }, { id: "journal", label: "最新內容", href: "/journal", order: 3, visibility: "published" as const }],
  home: { id: "home" as const, hero: { title: "追劇，是開始。", subtitle: "創作，才是你的主場。", ctaLabel: "下載 APP", ctaHref: "/download" }, brandStatement: { title: "追劇 × 創作 × 分享" }, viewerCreator: { title: "從觀看到創作" }, dramaDiscovery: { title: "探索短劇" }, creatorCenter: { title: "創作者中心" }, creatorFeed: { title: "創作動態" }, rewards: { title: "任務與獎勵" }, profile: { title: "個人中心" }, latestContent: { title: "最新內容" }, journal: { title: "My Dream Journal" }, downloadCTA: { title: "下一個故事，從 My Dream 開始。", ctaLabel: "下載 APP", ctaHref: "/download" }, visibility: "published" as const },
  dramaCategories: [{ id: "drama-emotion", slug: "emotion", name: "情感", description: "情感與關係故事。", order: 1, kind: "drama" as const, contentStatus: "published" as const }, { id: "drama-wealth", slug: "wealth", name: "豪門", description: "都會與豪門題材。", order: 2, kind: "drama" as const, contentStatus: "published" as const }],
  articleCategories: [{ id: "article-recommendation", slug: "recommendation", name: "短劇推薦", description: "短劇內容推薦。", order: 1, kind: "article" as const, contentStatus: "published" as const }],
  dramas: [{ id: "drama-love-after-rain", slug: "love-after-rain", title: "雨後的心動", synopsis: "待正式短劇資料核定後發布。", categoryIds: ["drama-emotion"], categories: ["情感"], tags: ["治癒"], poster: placeholderPoster, episodes: 48, availability: "upcoming" as const, featured: true, publicationStatus: "draft" as const }, { id: "drama-ceo-secret", slug: "ceo-secret", title: "總裁的秘密劇本", synopsis: "待正式短劇資料核定後發布。", categoryIds: ["drama-wealth"], categories: ["豪門"], tags: ["反轉"], poster: placeholderPoster, episodes: 60, availability: "upcoming" as const, featured: false, publicationStatus: "draft" as const }],
  creators: [] as Creator[],
  articles: [{ id: "article-short-drama-guide", slug: "summer-short-drama-guide", title: "本週值得追的短劇", excerpt: "待編輯部審核後發布。", categoryId: "article-recommendation", category: "短劇推薦", cover: placeholderPoster, author: "My Dream 編輯部", publishedAt: "2026-07-21", body: ["此為內容模型的草稿資料，不能作為正式上線文章。"], featured: true, publicationStatus: "draft" as const }],
  legal: [{ id: "legal-privacy", slug: "privacy" as const, title: "隱私權政策", version: "draft", body: ["正式法務文字尚待核定。"], publicationStatus: "draft" as const }, { id: "legal-terms", slug: "terms" as const, title: "服務條款", version: "draft", body: ["正式法務文字尚待核定。"], publicationStatus: "draft" as const }],
  business: { id: "business" as const, title: "商務合作", description: "歡迎內容、短劇、創作者與品牌合作。", visibility: "published" as const },
  downloadSettings: { id: "download-settings" as const, ios: { availability: "coming-soon" as const }, googlePlay: { availability: "coming-soon" as const }, android: { availability: "coming-soon" as const }, qrCodeStatus: "coming-soon" as const, deepLinkStatus: "coming-soon" as const },
};

function applyOptions<T extends { id?: string; title?: string; displayName?: string; categoryIds?: string[]; categoryId?: string }>(items: T[], options?: ListOptions): T[] { const query = options?.query?.trim().toLocaleLowerCase("zh-Hant"); const filtered = items.filter((item) => (!options?.ids?.length || (item.id && options.ids.includes(item.id))) && (!options?.category || item.categoryIds?.includes(options.category) || item.categoryId === options.category) && (!query || `${item.title ?? ""} ${item.displayName ?? ""}`.toLocaleLowerCase("zh-Hant").includes(query))); return options?.limit ? filtered.slice(0, options.limit) : filtered; }

export class LocalContentProvider implements ContentRepository {
  private readonly production = process.env.NODE_ENV === "production";
  private readonly site = SiteSettingsSchema.parse(localContent.site); private readonly navigation = localContent.navigation.map((item) => NavigationItemSchema.parse(item)); private readonly home = HomePageSchema.parse(localContent.home); private readonly dramaCategories = localContent.dramaCategories.map((item) => DramaCategorySchema.parse(item)); private readonly articleCategories = localContent.articleCategories.map((item) => ArticleCategorySchema.parse(item)); private readonly dramas = localContent.dramas.map((item) => DramaSchema.parse(item)); private readonly creators = localContent.creators; private readonly articles = localContent.articles.map((item) => ArticleSchema.parse(item)); private readonly legal = localContent.legal.map((item) => LegalPageSchema.parse(item)); private readonly business = BusinessPageSchema.parse(localContent.business); private readonly downloadSettings = DownloadSettingsSchema.parse(localContent.downloadSettings);
  async getSite(): Promise<Site> { return this.site; } async getSiteSettings(): Promise<Site> { return this.site; } async getNavigation(): Promise<NavigationItem[]> { return filterProductionContent(this.navigation, this.production).sort((a, b) => a.order - b.order); } async getHomePage(): Promise<HomePage> { return this.home; }
  async listDramas(options?: ListOptions): Promise<Drama[]> { return applyOptions(filterProductionContent(this.dramas, this.production), options); } async getDramas(options?: ListOptions): Promise<Drama[]> { return this.listDramas(options); } async getFeaturedDramas(): Promise<Drama[]> { return (await this.getDramas()).filter((item) => item.featured); } async getDramaBySlug(slug: string): Promise<Drama | null> { return (await this.getDramas()).find((item) => item.slug === slug) ?? null; } async getDramaCategories(): Promise<DramaCategory[]> { return filterProductionContent(this.dramaCategories, this.production).sort((a, b) => a.order - b.order); }
  async listCreators(options?: ListOptions): Promise<Creator[]> { return applyOptions(filterProductionContent(this.creators, this.production), options); } async getCreators(options?: ListOptions): Promise<Creator[]> { return this.listCreators(options); } async getFeaturedCreators(): Promise<Creator[]> { return (await this.getCreators()).filter((item) => item.featured); } async getCreatorBySlug(slug: string): Promise<Creator | null> { return (await this.getCreators()).find((item) => item.slug === slug) ?? null; }
  async listArticles(options?: ListOptions): Promise<Article[]> { return applyOptions(filterProductionContent(this.articles, this.production), options); } async getArticles(options?: ListOptions): Promise<Article[]> { return this.listArticles(options); } async getFeaturedArticles(): Promise<Article[]> { return (await this.getArticles()).filter((item) => item.featured); } async getArticleBySlug(slug: string): Promise<Article | null> { return (await this.getArticles()).find((item) => item.slug === slug) ?? null; } async getArticleCategories(): Promise<ArticleCategory[]> { return filterProductionContent(this.articleCategories, this.production).sort((a, b) => a.order - b.order); }
  async getLegalDocument(slug: LegalDocument["slug"]): Promise<LegalDocument | null> { return filterProductionContent(this.legal, this.production).find((item) => item.slug === slug) ?? null; } async getLegalPage(type: LegalDocument["slug"]): Promise<LegalDocument | null> { return this.getLegalDocument(type); } async getBusinessPage(): Promise<BusinessPage> { return this.business; } async getDownloadSettings(): Promise<DownloadSettings> { return sanitizeDownloadSettings(this.downloadSettings); }
}
