CREATE TABLE cms_creator_settings_sync (
 project_id CHAR(36) PRIMARY KEY,
 revision INT NOT NULL DEFAULT 1,
 state VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 message VARCHAR(500) NOT NULL DEFAULT '',
 claim_token CHAR(36) NULL,
 claimed_at TIMESTAMP NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE cms_creator_notification_read (
 owner_key VARCHAR(191) NOT NULL,
 notification_id VARCHAR(100) NOT NULL,
 read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(owner_key,notification_id)
);
CREATE TABLE cms_creator_material_review (
 project_id CHAR(36) PRIMARY KEY,
 version INT NOT NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'PENDING',
 note VARCHAR(1000) NOT NULL DEFAULT '',
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
