"use client";
import {useEffect,useState} from "react";
type Row=Record<string,unknown>;
const labels:Record<string,string>={drama:"劇目",episode:"劇集",withdrawal:"提現",video:"視頻",project:"項目",verification:"身份審核",agreement:"協議審核",team:"企業權限",INSERT:"新增",UPDATE:"修改 / 上下架",DELETE:"刪除",MANUAL_PAID:"確認人工付款",REJECT_REFUND:"驳回並退回積分"};
function object(value:unknown):Row{try{const parsed=typeof value==="string"?JSON.parse(value):value;return parsed&&typeof parsed==="object"?parsed:{};}catch{return {};}}
function time(value:unknown){if(!value)return "—";const d=new Date(typeof value==="number"?value*1000:String(value));return Number.isNaN(d.getTime())?"—":d.toLocaleString("zh-TW");}
export function AppOperationsPanel({finance=false}:{finance?:boolean}){
 const [page,setPage]=useState(1),[revision,setRevision]=useState(0),[filter,setFilter]=useState({source:"creator",entity:"",id:""}),[query,setQuery]=useState(filter);
 const [data,setData]=useState<{rows:Row[];total:number}|null>(null),[error,setError]=useState("");
 useEffect(()=>{const c=new AbortController();fetch('/api/app-admin/operations?'+new URLSearchParams({view:finance?"withdrawals":"audit",page:String(page),...query}),{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message||"讀取失敗");setData(d);setError("");}).catch(e=>{if(!c.signal.aborted){setData(null);setError(e.message);}});return()=>c.abort();},[finance,page,revision,query]);
 return <section className="app-operations-panel"><p className="admin-muted">{finance?"此處同步 App 提現記錄。審核、駁回及付款結果請在右上角「完整管理後台」處理。":"顯示創作者平台最近 500 條審核、項目變更與企業權限記錄。不包含 App 內部操作，歷史缺失不推測操作者。"}</p>
 <form className="app-admin-search" onSubmit={e=>{e.preventDefault();setPage(1);setQuery({...filter});setRevision(v=>v+1);}}>{!finance&&<><select aria-label="記錄類型" value={filter.entity} onChange={e=>setFilter({...filter,entity:e.target.value})}><option value="">全部類型</option>{["project","verification","agreement","team"].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select><input aria-label="記錄編號" placeholder="項目 / 審核 / 企業 ID" value={filter.id} onChange={e=>setFilter({...filter,id:e.target.value})}/></>}<button className="admin-primary">查詢 / 刷新</button></form>
 {error&&<p className="admin-form-error" role="alert">{error}</p>}
 <div className="app-admin-table"><table><thead><tr><th>編號 / 時間</th><th>{finance?"申請與金額":"對象與操作"}</th><th>{finance?"處理狀態":"操作人"}</th><th>詳情</th></tr></thead><tbody>{data?.rows.map(row=><tr key={String(row.id)}><td>#{String(row.id)}<small>{time(row.created_at)}</small></td><td>{finance?<>{String(object(row.user).username||"—")}<small>申請 {String(row.amount)} 積分 · 實付 {String(row.actual_amount)} 元</small></>:<>{labels[String(row.entity_type)]||String(row.entity_type)} #{String(row.entity_id)}<small>{labels[String(row.action)]||String(row.action)}</small></>}</td><td>{finance?({"0":"待處理","1":"已付款","2":"已驳回"}[String(row.status)]||"待核對"):String(row.actor)}</td><td>{finance?<>{row.reason&&<p>{String(row.reason)}</p>}{String(row.status)==="0"&&<small>請在完整管理後台處理</small>}</>:<details><summary>查看變更前後</summary><table><thead><tr><th>字段</th><th>原值</th><th>新值</th></tr></thead><tbody>{[...new Set([...Object.keys(object(row.before_json)),...Object.keys(object(row.after_json))])].filter(key=>object(row.before_json)[key]!==object(row.after_json)[key]).map(key=><tr key={key}><td>{key}</td><td>{String(object(row.before_json)[key]??"—")}</td><td>{String(object(row.after_json)[key]??"—")}</td></tr>)}</tbody></table></details>}</td></tr>)}</tbody></table>{data&&!data.rows.length&&<p>暫無記錄</p>}</div>
 <div className="app-admin-pagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>上一頁</button><span>第 {page} 頁 · {data?.total??0} 條</span><button disabled={!data||page*20>=data.total} onClick={()=>setPage(v=>v+1)}>下一頁</button></div>
 </section>;
}
