/* eslint-disable @next/next/no-img-element -- private certification images are not public media assets. */
"use client";
import { useEffect, useState } from "react";
import { creatorTypes, entityTypes, verificationLabels, type Verification } from "@/lib/creator-auth/verification";
type Row=Verification & {id:string;username:string;submittedAt:string};
type Detail=Verification & {id:string;payload:{name:string;documentNumber:string;contactName?:string;contact:string;region:string;profile?:Record<string,string>;documents:{name:string;data:string;kind?:string}[]};history:{action:string;note:string;actor:string;createdAt:string}[]};
async function api<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(`/api/creator/verification-reviews${path}`,{method:body?"POST":"GET",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await r.json();if(!r.ok)throw new Error(data.detail||"認證審核服務暫時不可用");return data;}
export function VerificationReviewPanel(){
 const [rows,setRows]=useState<Row[]>([]),[detail,setDetail]=useState<Detail|null>(null),[filter,setFilter]=useState("PENDING"),[note,setNote]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;api<Row[]>("").then(data=>{if(active){setRows(data);setError("");}}).catch(e=>{if(active)setError(e.message);});return ()=>{active=false;};},[revision]);
 async function open(id:string){setBusy(true);setError("");try{setDetail(await api<Detail>(`/${id}`));setNote("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decide(decision:string){if(!detail)return;setBusy(true);setError("");try{await api(`/${detail.id}`,{decision,note,version:detail.version});setDetail(null);setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="verification-review"><header><div><p>官網創作者認證</p><h2>身份認證審核</h2></div><button onClick={()=>setRevision(v=>v+1)} disabled={busy}>刷新列表</button></header><p>提交資料的創作者可正常進入平台；審核通過後開啟正式發佈權限。</p><label>審核狀態 <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">全部申請</option>{(["PENDING","APPROVED","REJECTED"] as const).map(s=><option key={s} value={s}>{verificationLabels[s]}</option>)}</select></label>{error&&<p role="alert" className="admin-form-error">{error}</p>}<div className="verification-review-table"><table><thead><tr><th>創作者賬號</th><th>創作身份</th><th>認證主體</th><th>狀態</th><th>操作</th></tr></thead><tbody>{rows.filter(r=>filter==="ALL"||r.state===filter).map(row=><tr key={row.id}><td>{row.username}</td><td>{row.creatorType&&creatorTypes[row.creatorType]}</td><td>{row.entityType&&entityTypes[row.entityType]}</td><td>{verificationLabels[row.state]}</td><td><button disabled={busy} onClick={()=>void open(row.id)}>查看資料{row.state==="PENDING"?"並審核":""}</button></td></tr>)}</tbody></table>{!rows.some(r=>filter==="ALL"||r.state===filter)&&<p>暫無此狀態的認證申請</p>}</div>{detail&&<section className="verification-review-detail"><header><h3>認證資料</h3><button disabled={busy} onClick={()=>setDetail(null)}>關閉資料</button></header><dl>{[["姓名／企業名稱",detail.payload.name],["國家或地區",detail.payload.region],["證件／登記編號",detail.payload.documentNumber],["企業聯絡人",detail.payload.contactName],["聯絡方式",detail.payload.contact],...Object.entries(detail.payload.profile||{}).map(([key,value])=>[({displayName:"創作者 / 品牌名稱",email:"電子郵箱",phone:"聯絡電話",city:"所在城市",address:"企業登記地址",introduction:"創作簡介",portfolioUrl:"作品集連結",representative:"企業負責人",contactRole:"聯絡人職務",documentType:"證件類型"} as Record<string,string>)[key]||key,({ID_CARD:"身份證",PASSPORT:"護照",BUSINESS_LICENSE:"企業登記證明"} as Record<string,string>)[value]||value])].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||"—"}</dd></div>)}</dl><div className="verification-documents">{detail.payload.documents.map((document,i)=><figure key={i}><img src={document.data} alt={`認證證明 ${i+1}`}/><figcaption>{({ID_FRONT:"證件正面",ID_BACK:"證件背面",PASSPORT:"護照資料頁",HANDHELD:"本人手持證件",BUSINESS_LICENSE:"企業登記證明",AUTHORIZATION:"企業授權書"} as Record<string,string>)[document.kind||""]||`認證證明 ${i+1}`}</figcaption></figure>)}</div><p>{detail.reviewNote}</p>{detail.state==="PENDING"&&<><label>審核意見（退回必填）<textarea rows={3} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></label><div className="verification-actions"><button disabled={busy||!note.trim()} onClick={()=>void decide("REJECTED")}>退回補充資料</button><button className="admin-primary" disabled={busy} onClick={()=>void decide("APPROVED")}>通過認證</button></div></>}<details><summary>審核記錄</summary>{detail.history.map((event,i)=><p key={i}>{event.createdAt} · {event.action} · {event.actor} {event.note}</p>)}</details></section>}</section>;
}
