package com.mydream.cms.creator;
import static org.assertj.core.api.Assertions.*;
import com.mydream.cms.config.CmsProperties;
import com.mydream.cms.forms.PiiCipher;
import com.mydream.cms.shared.ApiException;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.test.util.ReflectionTestUtils;
import tools.jackson.databind.ObjectMapper;
@EnabledIfEnvironmentVariable(named="CREATOR_TEAM_TEST_DB",matches="jdbc:mysql://127.0.0.1:3309/creator_team_test(?:\\?.*)?")
class CreatorTeamIntegrationTest {
 @Test void invitationIsolationRevocationAndOwnerIdentity(){
  var ds=new DriverManagerDataSource(System.getenv("CREATOR_TEAM_TEST_DB"),"root","");var jdbc=new JdbcTemplate(ds);
  for(String t:List.of("cms_creator_cooperation_draft","cms_creator_team_member","cms_creator_team_context","cms_creator_team_audit","cms_creator_verification","cms_creator_session","cms_creator_account"))jdbc.execute("DROP TABLE IF EXISTS "+t);
  new ResourceDatabasePopulator(new ClassPathResource("db/migration/V29__creator_accounts.sql"),new ClassPathResource("db/migration/V37__creator_company_teams.sql"),new ClassPathResource("db/migration/V41__creator_member_roles.sql")).execute(ds);
  jdbc.execute("CREATE TABLE cms_creator_verification(owner_key VARCHAR(64) PRIMARY KEY,entity_type VARCHAR(16),state VARCHAR(16),payload_encrypted TEXT) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
  var cipher=new PiiCipher(new CmsProperties(null,null,null,null,null,Base64.getEncoder().encodeToString(new byte[32]),null,null,null,null));var mapper=new ObjectMapper();
  var teams=new CreatorTeamService(jdbc,cipher,mapper);var accounts=new CreatorAccountService(jdbc,new BCryptPasswordEncoder(4),cipher,mapper,"http://127.0.0.1:1");ReflectionTestUtils.setField(accounts,"teams",teams);
  var boss=accounts.register("team_boss","Creator12345",null,true);var member=accounts.register("team_member","Creator12345",null,true);var other=accounts.register("team_other","Creator12345",null,true);
  String owner=boss.account().id(),actor=member.account().id();
  assertThatThrownBy(()->teams.invite(owner,new CreatorTeamService.Invite("team_member",true,true,false))).isInstanceOf(ApiException.class);
  jdbc.update("INSERT INTO cms_creator_verification VALUES (?,'BUSINESS','APPROVED',?)","creator:"+owner,cipher.encrypt("{\"name\":\"Synthetic Company\"}"));
  teams.invite(owner,new CreatorTeamService.Invite("team_member",true,true,false));
  assertThat(accounts.viewer(member.token()).ownerKey()).isEqualTo("creator:"+actor);
  assertThatThrownBy(()->teams.choose(actor,owner,"ENTER")).isInstanceOf(ApiException.class);
  assertThatThrownBy(()->teams.choose(other.account().id(),owner,"ACCEPT")).isInstanceOf(ApiException.class);
  teams.choose(actor,owner,"ACCEPT");
  assertThat(accounts.viewer(member.token()).ownerKey()).isEqualTo("creator:"+owner);
  assertThat(accounts.viewer(other.token()).ownerKey()).isEqualTo("creator:"+other.account().id());
  assertThat(teams.appOwner(actor,"UPLOAD")).isEqualTo(owner);
  assertThatThrownBy(()->accounts.appSession(member.token())).isInstanceOf(ApiException.class).hasMessageContaining("權限");
  assertThatThrownBy(()->teams.appOwner(actor,"SUBMIT")).isInstanceOf(ApiException.class);
  assertThatThrownBy(()->teams.change(actor,new CreatorTeamService.Change(actor,"PERMISSIONS",true,true,true))).isInstanceOf(ApiException.class);
  assertThat(teams.status(actor)).doesNotContainKeys("members","history");
  teams.audit(owner,actor,"upload");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM cms_creator_team_audit WHERE company_owner=? AND actor_id=?",Integer.class,owner,actor)).isEqualTo(2);
  teams.change(owner,new CreatorTeamService.Change(actor,"PERMISSIONS",false,false,true));
  assertThatThrownBy(()->teams.appOwner(actor,"UPLOAD")).isInstanceOf(ApiException.class);assertThat(teams.appOwner(actor,"SUBMIT")).isEqualTo(owner);
  teams.change(owner,new CreatorTeamService.Change(actor,"PERMISSIONS",false,false,false,"OPERATOR",null));
  assertThat(teams.appOwner(actor,"TRAFFIC")).isEqualTo(owner);
  assertThatThrownBy(()->teams.appOwner(actor,"TRAFFIC_EXPORT")).isInstanceOf(ApiException.class);
  assertThatThrownBy(()->teams.appOwner(actor,"")).isInstanceOf(ApiException.class);
  teams.change(owner,new CreatorTeamService.Change(actor,"PERMISSIONS",false,false,false,"ANALYST",null));
  assertThat(teams.appOwner(actor,"TRAFFIC_EXPORT")).isEqualTo(owner);
  assertThatThrownBy(()->teams.appOwner(actor,"UPLOAD")).isInstanceOf(ApiException.class);
  teams.change(owner,new CreatorTeamService.Change(actor,"PERMISSIONS",false,false,false,"VIEWER",null));
  assertThatThrownBy(()->teams.appOwner(actor,"TRAFFIC")).isInstanceOf(ApiException.class);
  teams.change(owner,new CreatorTeamService.Change(actor,"PERMISSIONS",false,false,false,"BUSINESS",null));
  jdbc.execute("DROP TABLE IF EXISTS cms_creator_ip_interest");jdbc.execute("DROP TABLE IF EXISTS cms_creator_agreement");
  jdbc.execute("CREATE TABLE cms_creator_ip_interest(id VARCHAR(36),owner_key VARCHAR(100),work_title VARCHAR(100),status VARCHAR(30),proposal TEXT,review_note TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  jdbc.execute("CREATE TABLE cms_creator_agreement(id VARCHAR(36),owner_key VARCHAR(100),title VARCHAR(100),kind VARCHAR(30),state VARCHAR(30),body TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
  jdbc.update("INSERT INTO cms_creator_agreement(id,owner_key,title,kind,state,body) VALUES ('contract',?,'Contract','PROJECT','SUBMITTED','SECRET_FULL_CONTRACT')","creator:"+owner);
  var business=new CreatorBusinessController(teams,accounts,jdbc);var request=new org.springframework.mock.web.MockHttpServletRequest();request.addHeader("Authorization","Bearer "+member.token());
  String payload=mapper.writeValueAsString(business.list(request));assertThat(payload).contains("Contract").doesNotContain("SECRET_FULL_CONTRACT");
  var draft=(Map<?,?>)business.save(new CreatorBusinessController.Draft(null,"Plan","Internal draft",0),request);String draftId=draft.get("id").toString();
  assertThatThrownBy(()->business.save(new CreatorBusinessController.Draft(draftId,"Plan","Stale",0),request)).isInstanceOf(ApiException.class);
  business.save(new CreatorBusinessController.Draft(draftId,"Plan","Updated",1),request);
  teams.change(owner,new CreatorTeamService.Change(actor,"PERMISSIONS",false,false,false,"VIEWER",null));
  assertThatThrownBy(()->business.list(request)).isInstanceOf(ApiException.class);
  assertThatThrownBy(()->business.save(new CreatorBusinessController.Draft(null,"Denied","",0),request)).isInstanceOf(ApiException.class);
  teams.change(owner,new CreatorTeamService.Change(actor,"REMOVE",false,false,false));
  assertThatThrownBy(()->accounts.viewer(member.token())).isInstanceOf(ApiException.class);
  assertThat(teams.status(actor).get("unavailable")).isEqualTo(true);
  assertThat(accounts.viewer(boss.token()).ownerKey()).isEqualTo("creator:"+owner);
  teams.choose(actor,null,"PERSONAL");assertThat(accounts.viewer(member.token()).ownerKey()).isEqualTo("creator:"+actor);
 }
}
