"use client";
import {useCompanyPermissions} from "./company-team";
import { useEffect, useImperativeHandle, useState, type Ref } from "react";
import { Plus, X, FileCheck2, RefreshCw } from "lucide-react";
import type { AgreementData } from "@/lib/creator-agreements";
import "./project-materials.css";
import { projectAreas, projectCategories, type ProjectSettings } from "@/lib/creator-video/project-settings";
type Attachment={kind:string;name:string;data:string};
type Materials={fields:Record<string,string>;documents:Attachment[];version:number;locked:boolean;updateStatus:string;reviewState?:string;reviewNote?:string;reviewUpdatedAt?:string;history?:{note:string;createdAt:string}[]};
export type MaterialsHandle={save:()=>Promise<boolean>};
const sections=[["shell","劇殼信息"],["basic","基礎信息"],["team","製作團隊"],["filing","備案信息"],["contract","合同信息"],["rights","版權信息"]];
export function ProjectMaterials({projectId,admin=false,disabled=false,handle}:{projectId:string;admin?:boolean;disabled?:boolean;handle?:Ref<MaterialsHandle>}){
 const permissions=useCompanyPermissions();
 const [value,setValue]=useState<Materials|null>(null),[error,setError]=useState(""),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[revision,setRevision]=useState(0),[contracts,setContracts]=useState<AgreementData["contracts"]>([]);
 const [reviewNote,setReviewNote]=useState("");
 const [project,setProject]=useState<{episodeCount:number;genre:string;format:string;title:string;synopsis:string;settings?:ProjectSettings}|null>(null);
 const prefix=admin?"project-reviews":"projects",path=`/api/creator/${prefix}/${projectId}/materials`;
 useEffect(()=>{const controller=new AbortController();
 fetch(path,{cache:"no-store",signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||"資料讀取失敗");return d;}).then(v=>{if(!controller.signal.aborted){setValue(v);setError("");setDirty(false);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});
 fetch(`/api/creator/${prefix}/${projectId}`,{cache:"no-store",signal:controller.signal}).then(r=>r.ok?r.json():null).then(setProject).catch(()=>{});
 if(!admin&&!permissions.member)fetch("/api/creator/contracts",{cache:"no-store",signal:controller.signal}).then(r=>r.ok?r.json():null).then(d=>setContracts(d?.contracts?.filter((c:AgreementData["contracts"][number])=>c.scope===projectId||c.scope==="membership")||[])).catch(()=>{});
 return()=>controller.abort();},[path,projectId,prefix,admin,revision,permissions.member]);
 const locked=!permissions.canEdit||admin||(disabled&&value?.reviewState!=="CHANGES_REQUESTED")||!!value?.locked||busy;
 const change=(key:string,text:string)=>{setValue(v=>v?{...v,fields:{...v.fields,[key]:text}}:v);setDirty(true);setNotice("");};
 async function save(){if(busy)return false;if(!project?.title?.trim()||!project.synopsis?.trim()||!project.episodeCount||!project.settings?.area||!projectCategories[project.settings.area]?.some(c=>c.value===project.settings?.category)||project.settings.landscape===undefined||project.settings.price===undefined){setError("請先在項目中完善上架必填資料，再繼續上傳");return false;}if(!dirty&&!permissions.canEdit)return true;if(!dirty&&!(value?.version&&value.reviewState==="UNREVIEWED"))return true;if(!value)return false;if(locked){setError("資料已鎖定，請刷新確認");return false;}setBusy(true);setError("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const d=await r.json();if(!r.ok)throw Error(d.detail||"資料保存失敗");setValue(d);setDirty(false);setNotice("資料已提交審核，結果會在消息中心通知你。");return true;}catch(e){setError(e instanceof Error?e.message:"保存失敗");return false;}finally{setBusy(false);}}
 useImperativeHandle(handle,()=>({save}));
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
 async function upload(kind:string,file?:File){if(!file||locked)return;setBusy(true);setError("");try{if(!["image/jpeg","image/png","application/pdf"].includes(file.type)||file.size>5*1024*1024||!file.size||(kind.endsWith("Cover")&&file.type==="application/pdf"))throw Error("請使用 5 MB 內的 JPG、PNG 或 PDF；封面只支持圖片");
 const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error("文件讀取失敗"));reader.readAsDataURL(file);});
 const docs=[...(value?.documents||[]).filter(d=>d.kind!==kind||kind==="projectScreenshot"),{kind,name:file.name,data}];
 if(docs.length>10||docs.reduce((sum,d)=>sum+Math.floor((d.data.length-d.data.indexOf(",")-1)*.75),0)>12*1024*1024)throw Error("附件最多 10 份，合計不超過 12 MB");
 setValue(v=>v?{...v,documents:docs}:v);setDirty(true);setNotice("");}catch(e){setError(e instanceof Error?e.message:"讀取失敗");}finally{setBusy(false);}}
 async function review(state:string){if(!value)return;setBusy(true);setError("");try{const r=await fetch(`/api/creator/project-reviews/${projectId}/materials-review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,note:reviewNote,version:value.version})});const d=await r.json();if(!r.ok)throw Error(d.detail||"審核保存失敗");setRevision(n=>n+1);setReviewNote("");}catch(e){setError(e instanceof Error?e.message:"審核失敗");}finally{setBusy(false);}}
 const field=(key:string,label:string,options?:string[])=> <label className="pm-field" key={key}><span>{label}</span>{options?<select disabled={locked} value={value?.fields[key]||""} onChange={e=>change(key,e.target.value)}><option value="">請選擇</option>{options.map(option=><option key={option}>{option}</option>)}</select>:<input disabled={locked} maxLength={key==="characters"?2000:200} value={value?.fields[key]||""} onChange={e=>change(key,e.target.value)} placeholder={key==="characters"?"填寫角色名稱及簡介，每個角色以分號分隔":"請填寫"}/>}</label>;
 const attachment=(kind:string,label:string,ratio?:string)=><div className="pm-attachment" key={kind}><span>{label}</span><div><div className="pm-files">{value?.documents.filter(d=>d.kind===kind).map((d,i)=><div key={`${kind}-${i}`}>{d.data.startsWith("data:image/")&&<img src={d.data} alt={label}/>}<a href={d.data} download={d.name}>{d.name}</a>{!locked&&<button type="button" aria-label={`移除${d.name}`} onClick={()=>{setValue(v=>v?{...v,documents:v.documents.filter(item=>item!==d)}:v);setDirty(true);}}><X size={14}/></button>}</div>)}</div>{!locked&&<label className={`pm-upload ${kind.endsWith("Cover")?"pm-cover":""}`}><Plus size={24}/><span>{value?.documents.some(d=>d.kind===kind)&&kind!=="projectScreenshot"?"替換文件":"點擊上傳"}</span><input type="file" accept={kind.endsWith("Cover")?"image/png,image/jpeg":"image/png,image/jpeg,application/pdf"} onChange={e=>{void upload(kind,e.target.files?.[0]);e.target.value="";}}/></label>}<small>{ratio?`建議比例 ${ratio} · JPG / PNG` :"JPG / PNG / PDF"} · 每份不超過 5 MB</small></div></div>;
 return <div className="pm-layout">
 {project&&<section className="pm-app-summary"><h3>項目必填資料 <small>已自動帶入，無需重填</small></h3><dl>{[["作品名稱",project.title],["作品簡介",project.synopsis],["總集數",`${project.episodeCount} 集`],["地區",projectAreas.find(a=>a.value===project.settings?.area)?.label||"尚未填寫"],["App 分類",projectCategories[project.settings?.area||""]?.find(c=>c.value===project.settings?.category)?.label||"尚未填寫"],["畫面方向",project.settings?(project.settings.landscape?"橫屏":"直屏"):"尚未填寫"],["單集解鎖價格",project.settings?.price??"尚未填寫"],["更新狀態",value?.updateStatus||"—"]].map(([label,text])=><div key={String(label)}><dt>{label}</dt><dd>{text}</dd></div>)}</dl>{!admin&&!permissions.member&&<a href={`#projects?project=${encodeURIComponent(projectId)}`}>前往項目修改上架資料</a>}</section>}
 <section className={`pm-workflow is-${value?.reviewState?.toLowerCase()||"new"}`} aria-label="補充資料審核進度"><header><span className="pm-workflow-icon"><FileCheck2 size={21}/></span><div><h3>補充資料審核 <span>{({PENDING:"待審核",APPROVED:"審核通過",CHANGES_REQUESTED:"待修改",UNREVIEWED:"待提交"} as Record<string,string>)[value?.reviewState||""]||"尚未提交"}</span></h3><p>{value?.version?`第 ${value.version} 版 · `:""}{value?.reviewState==="PENDING"?"資料已送交平台，審核期間不可修改。":value?.reviewState==="APPROVED"?"本版資料已確認。":value?.reviewState==="CHANGES_REQUESTED"?"請按以下意見修改，再重新提交審核。":"按實際需要補充，各集共用。"}</p></div><button type="button" aria-label="刷新資料審核狀態" disabled={busy||dirty} onClick={()=>setRevision(n=>n+1)}><RefreshCw size={15}/></button></header>{value?.reviewNote&&<blockquote><strong>平台審核意見</strong><p>{value.reviewNote}</p></blockquote>}{value?.reviewUpdatedAt&&<small>最近更新：{new Date(value.reviewUpdatedAt).toLocaleString("zh-TW")}</small>}{notice&&<p role="status" className="pm-submitted-notice">{notice}</p>}{!!value?.history?.length&&<details className="pm-review-history"><summary>查看提交與審核記錄 · {value.history.length} 條</summary>{value.history.map((event,i)=><div key={`${event.createdAt}-${i}`}><time>{new Date(event.createdAt).toLocaleString("zh-TW")}</time><p>{event.note}</p></div>)}</details>}</section>
 <details className="pm-supplement" open={error||value?.reviewState==="CHANGES_REQUESTED" ? true : undefined}><summary>補充審核資料 <small>選填 · 按實際需要補充</small></summary><nav aria-label="資料分區">{sections.map(([id,label])=><button key={id} type="button" onClick={()=>document.getElementById(`pm-${id}`)?.scrollIntoView({behavior:"smooth",block:"start"})}>{label}</button>)}</nav>
 {!value?<p role="status">{error||"正在讀取項目資料…"}{error&&<button type="button" onClick={()=>setRevision(n=>n+1)}>重新讀取</button>}</p>:<>

 {admin&&value.reviewState==="PENDING"&&<div className="pm-review-actions"><label>審核意見<textarea value={reviewNote} maxLength={1000} onChange={e=>setReviewNote(e.target.value)} placeholder="填寫確認意見或需補充的內容"/></label><div><button type="button" disabled={busy||!reviewNote.trim()} onClick={()=>void review("CHANGES_REQUESTED")}>退回補充</button><button type="button" disabled={busy||!reviewNote.trim()} onClick={()=>void review("APPROVED")}>確認資料</button></div></div>}
 <p className="pm-note">以下為本站審核資料，各集共用。{value.locked&&"目前資料已鎖定。"}</p>
 <section id="pm-shell"><h3>補充宣傳素材</h3><p className="pm-note">此處素材供審核參考；上架使用上方選擇的本集封面。</p>{attachment("portraitCover","補充豎版宣傳圖","7:10")}{attachment("posterCover","補充宣傳圖","2:3")}</section>
 <section id="pm-basic"><h3>基礎信息</h3>{field("paidAlias","站外付費別名")}{field("freeAlias","站外免費別名")}{field("isAi","是否 AI 作品",["是","否"])}{field("audience","適合觀眾",["男頻","女頻","通用"])}{field("series","是否系列劇",["是","否"])}{field("adaptation","是否 IP 改編",["是","否"])}</section>
 <section id="pm-team"><h3>製作團隊</h3>{field("company","製作機構")}{field("producer","製片人")}{field("director","導演")}{field("writer","編劇")}{field("characters","角色信息")}</section>
 <section id="pm-filing"><h3>備案信息</h3>{field("budgetRange","製作金額範圍",["30 萬以下","30 萬（含）至 80 萬","80 萬及以上"])}{field("productionCost","製作成本（含幣種）")}{attachment("costSheet","成本配置資料")}</section>
 <section id="pm-contract"><h3>合同信息</h3><label className="pm-field"><span>關聯合作合同</span><select disabled={locked} value={value.fields.contractId||""} onChange={e=>change("contractId",e.target.value)}><option value="">請選擇合同</option>{contracts.map(c=><option key={c.id} value={c.id}>{c.title||"合作協議"} · {c.id.slice(-8)}</option>)}{value.fields.contractId&&!contracts.some(c=>c.id===value.fields.contractId)&&<option value={value.fields.contractId}>{value.fields.contractId}</option>}</select></label>{!admin&&!permissions.member&&<a href={`#contracts?project=${encodeURIComponent(projectId)}`}>查看項目合作協議</a>}</section>
 <section id="pm-rights"><h3>版權信息</h3>{attachment("rights","權屬證明文件")}{attachment("promise","不侵權承諾函")}{attachment("projectScreenshot","工程文件截圖")}</section>
 {!admin&&<div className="pm-save"><button className="cw-outline" type="button" disabled={locked||(!dirty&&value.reviewState!=="UNREVIEWED")} onClick={()=>void save()}>{busy?"正在提交…":value.reviewState==="CHANGES_REQUESTED"?"重新提交審核":"提交資料審核"}</button><span role="status">{notice||(dirty?"有未保存的修改":"")}</span></div>}
 {error&&<p className="cw-error" role="alert">{error}</p>}
 </>}
 </details></div>;
}




