"use client";
import {useState} from "react";
import {projectAreas,projectCategories,type ProjectSettings} from "@/lib/creator-video/project-settings";
import type {EpisodeSubmission} from "./project-episodes";
type Options={dramas:{id:number;title:string}[];areas:{value:string;label:string}[];categories:{value:string;label:string}[]};
export function PublishEpisode({item,existingDramaId,onChanged,settings,recovery=false}:{recovery?:boolean;settings?:ProjectSettings|null;item:EpisodeSubmission;existingDramaId?:number;onChanged:()=>void}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[options,setOptions]=useState<Options|null>(null),[message,setMessage]=useState("");
 const [dramaId,setDramaId]=useState(existingDramaId?String(existingDramaId):""),[mode,setMode]=useState(existingDramaId?"existing":"new"),[search,setSearch]=useState("");
 async function load(){setBusy(true);setMessage("");try{const r=await fetch("/api/app-admin/project-publish?search="+encodeURIComponent(search),{cache:"no-store"});const data=await r.json();if(!r.ok)throw Error(data.message);setOptions(data);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function publish(){setBusy(true);setMessage("");try{const r=await fetch("/api/app-admin/project-publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId:item.projectId,submissionId:item.id,version:item.version,dramaId:mode==="existing"?Number(dramaId):undefined})});const data=await r.json();if(!r.ok)throw Error(data.message);setMessage(data.message);onChanged();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="cp-direct-publish"><button className="cw-primary" disabled={busy} onClick={()=>{setOpen(!open);if(!open)void load();}}>{recovery?"恢復發布 / 核對關聯":"上架到 App"}</button>{open&&<div className="cp-direct-publish-form"><h4>發佈第 {item.episodeNumber} 集 · {item.title}</h4><p>使用已審核的視頻及封面，上架後用戶可在 App 觀看。本操作也會將對應劇目設為已上架。</p><label>對應劇目<select value={mode} disabled={busy||!!existingDramaId} onChange={e=>setMode(e.target.value)}><option value="new">以本項目新建劇目</option><option value="existing">選擇已有劇目</option></select></label>{mode==="existing"?<><div className="cp-action"><input aria-label="搜尋 App 劇目" placeholder="搜尋劇目名稱" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy} onClick={()=>void load()}>搜尋</button></div><label>App 劇目<select value={dramaId} disabled={busy||!!existingDramaId} onChange={e=>setDramaId(e.target.value)}><option value="">請選擇劇目</option>{existingDramaId&&!options?.dramas.some(d=>d.id===existingDramaId)&&<option value={existingDramaId}>已關聯劇目 #{existingDramaId}</option>}{options?.dramas.map(d=><option key={d.id} value={d.id}>{d.title} · #{d.id}</option>)}</select></label></>:null}{settings?<p>項目資料：{projectAreas.find(a=>a.value===settings.area)?.label||settings.area} · {projectCategories[settings.area]?.find(c=>c.value===settings.category)?.label||settings.category} · {settings.landscape?"橫屏":"直屏"} · 單集解鎖價格 {Number(settings.price).toFixed(2)}</p>:<p role="alert">此項目缺少上架資料，請創作者在「我的項目」中補充。</p>}<div className="cp-action"><button disabled={busy} onClick={()=>setOpen(false)}>取消</button><button className="cw-primary" disabled={busy||!options||!settings||(mode==="existing"&&!dramaId)} onClick={()=>void publish()}>{busy?"正在處理…":recovery?"確認恢復發布":"確認上架到 App"}</button></div>{message&&<p role="status">{message}</p>}</div>}</section>;
}
