"use client";
import {FilmEmpty} from "./workspace-panels";
import {useEffect,useState} from "react";
import {useCompanyPermissions} from "./company-team";
import {hasPermission} from "@/lib/creator-team/roles";
import {csvCell,totalMetric,type AnalyticsVideo} from "@/lib/creator-analytics";
type Traffic={videos:AnalyticsVideo[];complete:boolean;projectComplete?:boolean;updatedAt:string};
export function TeamTraffic(){
 const permissions=useCompanyPermissions(),[data,setData]=useState<Traffic|null>(null),[error,setError]=useState(""),[revision,setRevision]=useState(0),[search,setSearch]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();setData(null);setError("");fetch("/api/creator-traffic",{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.message||"流量讀取失敗");return d;}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[revision]);
 async function download(){setBusy(true);setError("");try{const r=await fetch("/api/creator-traffic?export=1",{cache:"no-store"});const d:Traffic & {message?:string}=await r.json();if(!r.ok)throw Error(d.message||"沒有導出權限");const rows=[["作品","播放","點贊","評論","收藏"],...d.videos.filter(v=>v.title.includes(search)).map(v=>[v.title,v.views,v.likes,v.comments,v.collections])];const url=URL.createObjectURL(new Blob(["\ufeff"+rows.map(row=>row.map(csvCell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="企業作品流量.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const num=(n:number|null)=>n===null?"—":n.toLocaleString();
 return <section className="cw-card rp-panel rp-team-data"><div className="cw-card-title"><div><h1 className="cw-page-title">作品流量</h1><p>當前企業創作身份下的項目劇集流量</p></div><button onClick={()=>setRevision(v=>v+1)}>刷新數據</button></div>{error&&<p role="alert">{error}。如需更新企業 App 綁定，請聯絡總管理員。</p>}{!data&&!error&&<p role="status">正在讀取流量…</p>}{data&&<>{(!data.complete||data.projectComplete===false)&&<p role="status">部分數據尚未完整讀取；缺失值顯示為「—」，可稍後刷新。</p>}<div className="ct-traffic-totals">{([['views','累計播放'],['likes','累計點贊'],['comments','累計評論']] as const).map(([key,label])=><div key={key}><span>{label}</span><strong>{num(totalMetric(data.videos,key))}</strong></div>)}</div><div className="cw-list-toolbar rp-toolbar"><input aria-label="搜索企業作品" placeholder="搜索作品名稱" value={search} onChange={e=>setSearch(e.target.value)}/>{hasPermission(permissions,"traffic.export")&&<button disabled={busy} onClick={()=>void download()}>{busy?"正在導出…":"導出流量表格"}</button>}</div><div className="cw-table-scroll"><table className="cw-table"><thead><tr>{["作品","播放","點贊","評論","收藏"].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{data.videos.filter(v=>v.title.includes(search)).map(v=><tr key={v.id}><td>{v.title}</td>{[v.views,v.likes,v.comments,v.collections].map((n,i)=><td key={i}>{num(n)}</td>)}</tr>)}</tbody></table></div>{!data.videos.filter(v=>v.title.includes(search)).length&&<FilmEmpty title="暫無符合條件的作品流量"/>}<small>更新於 {new Date(data.updatedAt).toLocaleString("zh-TW")}；僅統計當前身份已關聯劇集，不包含另一類作品。</small></>}</section>;
}
