"use client";
import {useEffect,useState} from "react";
import {useCompanyPermissions} from "./company-team";
import {hasPermission} from "@/lib/creator-team/roles";
type Draft={id:string;title:string;body:string;version:number};
type Business={invitations:{id:string;title:string;status:string;proposal:string;reviewNote:string}[];contracts:{id:string;title:string;state:string;createdAt:string}[];drafts:Draft[]};
const states:Record<string,string>={PENDING:"待處理",CONTACTING:"洽談中",DECLINED:"未通過",SUBMITTED:"待審核",CHANGES_REQUESTED:"待修改",DEMO_ACTIVE:"演示確認生效"};
export function TeamBusiness({contractsOnly=false}:{contractsOnly?:boolean}){
 const permissions=useCompanyPermissions(),[data,setData]=useState<Business|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[revision,setRevision]=useState(0),[draft,setDraft]=useState<Draft|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{const c=new AbortController();fetch("/api/creator/team/business",{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||"讀取失敗");return d;}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[revision]);
 return <section className="cw-card"><div className="cw-card-title"><h1 className="cw-page-title">{contractsOnly?"合同摘要":"合作邀約"}</h1><button onClick={()=>{setError("");setRevision(v=>v+1);}}>刷新</button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p>正在讀取…</p>}{contractsOnly?<><p>僅展示合同基本狀態。全文、簽署與下載請聯絡總管理員。</p>{data?.contracts.map(c=><div className="ct-member" key={c.id}><div><strong>{c.title}</strong><small>{c.id}</small></div><span>{states[c.state]||"待確認"}</span></div>)}{data&&!data.contracts.length&&<p>暫無合同記錄</p>}</>:<>{data?.invitations.map(i=><div className="ct-member" key={i.id}><div><strong>{i.title}</strong><p>{i.proposal}</p><small>{i.reviewNote}</small></div><span>{states[i.status]||"待確認"}</span></div>)}{data&&!data.invitations.length&&<p>暫無合作邀約</p>}<h2>合作方案草稿</h2><p>供企業內部整理，不會自動發送或簽署合同。</p>{hasPermission(permissions,"cooperation.edit")&&<button onClick={()=>{setNotice("");setDraft({id:"",title:"",body:"",version:0});}}>新建草稿</button>}{data?.drafts.map(d=><div className="ct-member" key={d.id}><div><strong>{d.title}</strong><p style={{whiteSpace:"pre-wrap"}}>{d.body}</p></div>{hasPermission(permissions,"cooperation.edit")&&<button onClick={()=>setDraft(d)}>編輯</button>}</div>)}{draft&&<form className="ct-draft" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");try{const r=await fetch("/api/creator/team/business",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw Error(d.detail||"保存失敗");setDraft(null);setNotice("合作草稿已保存");setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy}><label>方案標題<input required maxLength={120} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>方案內容<textarea maxLength={5000} rows={6} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><button type="button" onClick={()=>setDraft(null)}>取消</button><button className="cw-primary">{busy?"保存中…":"保存草稿"}</button></fieldset></form>}</>}</section>;
}
